name: "sync submodule"

on:
        push:
                branches:
                        - main
        workflow_dispatch:
jobs:
        sync:
                runs-on: 'ubuntu-latest'
                steps:
                        - name: checkout repository
                          uses: actions/checkout@main
                        - name: submodules update
                          run: git submodule update --init --recursive
                        - name: foreach update
                          run: git submodule foreach git pull origin main
                        - name: commit changes
                          uses: github-actions-x/commit@2.7
                          with:
                            github-token: ${{ secrets.GITHUB_TOKEN }}
                            push-branch: 'main'
                            commit-message: "synchronization"



