name: "sync submodule"

on:
        push:
                branches:
                        - main
        workflow_dispatch:
jobs:
        sync:
                runs-on: 'ubuntu-latest'
                steps:
                        - name: checkout repository
                          uses: actions/checkout@master
                        - name: submodules update
                          uses: textbook/git-checkout-submodule-action@main
                          with:
                            remote: true