name: "sync submodule"

on:
        push:
                branches:
                        - main
        workflow_dispatch:
jobs:
        sync:
                runs-on: 'ubuntu-latest'
                steps:
                        - name: checkout repository
                          run: |
                            git submodule foreach git pull 
                          uses: github-actions-x/commit@v2.7
                          with:
                            github-token: ${{ secrets.GITHUB_TOKEN }}
                            push-branch: main
                            commit-message: "sync"
                                                      